### Get all goals
GET http://localhost:5001/api/goals
Accept: application/json

### Create new goal
POST http://localhost:5001/api/goals
Content-Type: application/json

{
  "text": "Track progress monthly"
}

### Update goal
PUT http://localhost:5001/api/goals/ab9cebab-db4c-451b-9d9a-19fcd3401dd1
Content-Type: application/json

{
  "text": "Track progress weekly"
}

### Delete goal
DELETE http://localhost:5001/api/goals/de384f7f-e10c-4b94-b264-b7cb5483bf0d